services:
  database:
    networks:
      - job
    container_name: job-mongodb
    image: mongo:latest
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.mongodb-job:/data/db
    ports:
      - ${DATABASE_BIND_PORT}:${DATABASE_PORT}
    command: ["mongod", "--port", "${DATABASE_PORT}"]

  api:
    depends_on:
      - database
    networks:
      - job
    container_name: job-api
    build:
      context: .
    image: api
    env_file:
      - .env
    environment:
      APPLICATION_PORT: ${APPLICATION_PORT}
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${APPLICATION_BIND_PORT}:${APPLICATION_PORT}

networks:
  job:
    driver: bridge
